### ISSUE TITLE
How To Remove(or reset) Previous InsertionQuery?

### ISSUE THREAD

**Issue by allenhwkim** [naugtur/insertionQuery#27]
First, thanks for this great work,

More like a question,

I see I can add an observer(?) like the following from READMD.md.

```
insertionQ('selector').every(function(element){
	//callback
});
```

How do I remove an observer?

I want to use this for SPA page to check if some section appear and disappear. I want to reset the observer when page changes, but not sure about it from README.md

**Comment by naugtur** [comment]
Hi, I'm glad you like it. 

While it might be possible, I haven't built a way to unsubscribe the function.

Please don't use insertionQuery for reasoning about views in your single page app. It scares me :)

I will use this opportunity to share some advice against using insertionQuery for organizing interface logic. What you need to do instead is think about communication architecture and maybe try leveraging the capabilities that are already there in your framework or just use an event emitter to send events from the parts that show/hide stuff to the code that depends on it. 
Single source of truth principle is pretty much what I'm advising here.

**Comment by allenhwkim** [comment]
Thanks for the reply

I wanted to build universal tracking functionality for angular application. 

Since tracking is not related to Angular  application features,  it's better to be built outside of the application and enabled by a line of javascript code like Google tracking.

IMO it's a valid feature to add and reset observers within s page

**Comment by naugtur** [comment]
While I don't have a lot of familiarity with angular, there's a principle that should apply to every browser based frontend - you shouldn't use DOM as storage for information or state. It will hurt you one way or another as the app grows.

You'll be much better off feeding an event emitter (or a Rx observable if you're in angular2) with data and subscribing to it. That way you get separation of concerns for the thing you refer to as tracking and maintain a sane approach to architecture while leaving DOM alone.

My best intuition is to compare it to screen pixels being rendered. Would you implement the same features if instead of DOM you had access to a screen buffer (canvas of sorts)? 
I implemented a sort of lemmings game in Pascal in my teens where I would read colors of pixels below the character to see if it should walk or fall down. There's a gap between what can be done and what is a good choice for a maintainable app.

Anyway, I agree cleanup is a valid feature for insertionQuery and I think I know how I'd approach fixing that. But unless you PR the feature, I'm probably not addressing it soon. This project is not a priority for me right now.

**Comment by naugtur** [comment]
I looked into the code to see if I could add it and noticed an undocumented feature I built in long ago. 
`.every` returns a reference with a .destroy function on it that cleans stuff up. 
```
const handle = insertionQ('selector').every(function(element){
	//callback
});
// later

handle.destroy()
```
